source: argodoll
title: Argonautica Dolls
url: https://argodoll.ru
cname: argodoll.ru
disqus_shortname: argodoll-ru
email: argodoll@gmail.com
permalink: pretty
markdown: kramdown
future: true
gems:
  - jekyll-sitemap

fb_app_id: 1556934541190558
